function Avatars() {
  "ngInject";

  this.icons = ['assistant.svg',
    'astronaut.svg',
    'businessman.svg',
    'captain.svg',
    'cashier.svg',
    'chef.svg',
    'concierge.svg',
    'cooker.svg',
    'courier.svg',
    'croupier-1.svg',
    'croupier.svg',
    'detective.svg',
    'disc-jockey.svg',
    'diver.svg',
    'doctor-1.svg',
    'doctor.svg',
    'engineer.svg',
    'farmer.svg',
    'firefighter-1.svg',
    'firefighter.svg',
    'gentleman.svg',
    'journalist.svg',
    'judge.svg',
    'loader.svg',
    'maid.svg',
    'manager.svg',
    'miner.svg',
    'motorcyclist.svg',
    'nun.svg',
    'nurse.svg',
    'pilot.svg',
    'policeman.svg',
    'postman.svg',
    'priest.svg',
    'scientist.svg',
    'sheriff.svg',
    'showman.svg',
    'soldier-1.svg',
    'soldier.svg',
    'stewardess.svg',
    'surgeon.svg',
    'swat.svg',
    'taxi-driver.svg',
    'teacher.svg',
    'thief.svg',
    'waiter.svg',
    'welder.svg',
    'worker-1.svg',
    'worker.svg',
    'writer.svg'
  ];
}

module.exports = Avatars;
