name: Build and Push frontend to GitHub Container Registry

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push frontend Docker image
        with:
          image: poll-frontend
          addLatest: true
          registry: ghcr.io
          # githubOrg: override-org # optional
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: frontend
          dockerfile: ./frontend/Dockerfile
